### ISSUE TITLE
getting error of emmit

### ISSUE THREAD

**Issue by codernirmalnp** [typestack/class-transformer#1573]
[Nest] 28240  - 07/23/2023, 1:48:28 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'emit')
TypeError: Cannot read properties of undefined (reading 'emit')
    at Object.socketOnTimeout [as timeout] (node:_http_server:587:37)
    at TransformOperationExecutor.transform (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\src\TransformOperationExecutor.ts:207:39)
    at TransformOperationExecutor.transform (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\src\TransformOperationExecutor.ts:327:31)
    at TransformOperationExecutor.transform (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\src\TransformOperationExecutor.ts:327:31)
    at TransformOperationExecutor.transform (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\src\TransformOperationExecutor.ts:327:31)
    at ClassTransformer.instanceToPlain (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\src\ClassTransformer.ts:25:21)
    at Object.classToPlain (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\src\index.ts:23:27)
    at ClassSerializerInterceptor.transformToPlain (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\@nestjs\common\serializer\class-serializer.interceptor.js:56:37)
    at ClassSerializerInterceptor.serialize (C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\@nestjs\common\serializer\class-serializer.interceptor.js:49:20)
    at C:\Users\Nirmal\Desktop\personal_project\typescript-starter\node_modules\@nestjs\common\serializer\class-serializer.interceptor.js:38:54
Error: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:372:5)
    at assert (node:internal/assert:14:11)
    at ServerResponse.detachSocket (node:_http_server:250:3)
    at resOnFinish (node:_http_server:824:7)
    at ServerResponse.emit (node:events:527:28)
    at onFinish (node:_http_outgoing:830:10)
    at callback (node:internal/streams/writable:552:21)
    at afterWrite (node:internal/streams/writable:497:5)
    at afterWriteTick (node:internal/streams/writable:484:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by metinjakupi** [comment]
up

**Comment by metinjakupi** [comment]
@codernirmalnp did you fix this ?

**Comment by nickfera** [comment]
> @codernirmalnp did you fix this ?

I was using the `ClassSerializerInterceptor` with the `app.useGlobalInterceptors()` and I was getting the same error.

```
app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));
```

I removed that and used it in the controller with `@UseInterceptors(ClassSerializerInterceptor)` and it's not giving me the error anymore.

**Comment by 5t33** [comment]
Also seeing this

**Comment by aaarab** [comment]
try to remove this line from your main.ts
app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));

**Comment by diffy0712** [comment]
The issue does not contain a simple reproduction case.

Closing as invalid.
