### ISSUE TITLE
question: Getting `ReferenceError: Cannot access 'XXX' before initialization` in class circular dependency with Jest & Typescript

### ISSUE THREAD

**Issue by Norlandz** [typestack/class-transformer#1622]
### Given 
I have 2 class, they have **circular dependency** on each other.
```ts
  class User {
    userName: string | undefined;
    @classTransformer.Type(() => Photo)
    photoFile: Photo | undefined;
  }

  class Photo {
    filename: string | undefined;
    @classTransformer.Type(() => User)
    owner: User | undefined;
  }
```
If I use them in normal Typescript code. Everything is **good**. 

### Problem
But when I use them in **Jest** (with Typescript), 
```ts
import * as classTransformer from 'class-transformer';
import 'reflect-metadata';

describe('sum', () => {
  class User {
    userName: string | undefined;
    @classTransformer.Type(() => Photo)
    photoFile: Photo | undefined;
  }

  class Photo {
    filename: string | undefined;
    @classTransformer.Type(() => User)
    owner: User | undefined;
  }

  it('basic', () => {
    console.log('aaaaaaaaaa');
  });
});
```
Following **error** is printed 
```
  ● Test suite failed to run

    ReferenceError: Cannot access 'Photo' before initialization

       5 |     userName: string | undefined;
       6 |     @classTransformer.Type(() => Photo)
    >  7 |     photoFile: Photo | undefined;
         |                ^
       8 |   }
       9 |
      10 |   class Photo {

      at src/main/index.test.ts:7:16
      at Object.<anonymous> (src/main/index.test.ts:3:1)
```

#### `any` Type
If I change the `Photo` Class Type to **`any`**, everything **works** again. (this is the current workaround)
```ts
  class User {
    userName: string | undefined;
    @classTransformer.Type(() => Photo)
    photoFile: any | undefined;
  }
```
#### remove `@Type`
If I remove `@Type`, code will run (but this is not a solution, cuz I need the `@Type`)

### related issue
https://github.com/typestack/class-transformer/issues/212#issuecomment-1704876169

**Comment by Norlandz** [comment]
It seems running with `ts-node` has such problem (/ `tsc` compiled js file), but running with `tsx` is fine.
Seems `Jest` uses `ts-node`.

**Comment by Norlandz** [comment]
More workarounds found 

### workaround -- `emitDecoratorMetadata` (so far the best)
> [] \
> The solution is to set `"emitDecoratorMetadata": false` in your tsconfig.json file. \
> <> \
> https://stackoverflow.com/questions/56870661/angular-7-2-1-es6-class-referenceerror-cannot-access-x-before-initializatio \
- but the problem is many other files need `emitDecoratorMetadata`, 
  I **cannot** specify a diff `tsconfig.json` for **each test file** in Jest (tried `jest.config.js`, just not working)

### other behavior
Use **array** `arr_photoFile: Photo[] = [];` may not have such problem. Depends on Jest Version though (newer ones fail). 
```ts
  class User {
    userName: string;
    @classTransformer.Type(() => Photo)
    arr_photoFile: Photo[] = [];

    constructor(userName: string) {
      this.userName = userName;
    }
  }

  class Photo {
    fileName: string;
    @classTransformer.Type(() => User)
    owner: User;

    constructor(fileName: string, owner: User) {
      this.fileName = fileName;
      this.owner = owner;
    }
  }
```
