### ISSUE TITLE
class-tranformer + class-validator -> problem with nested object validation

### ISSUE THREAD

**Issue by bkotrys** [typestack/class-transformer#226]
**Related to**: 
- https://github.com/typestack/class-transformer/issues/49
- https://github.com/typestack/class-validator/issues/306

I use `class-transformer` with `class-validator` to validate request body. I would like to validate class with nested object - **I need to check whether the given object is correct but don't allow to provide an array of objects** 

### How my implementation looks like:
```js
// Class definition with validation rules
class A {
  @IsDefined()
  @IsString()
  public x: string;
  // ... other properties
}

class B {
  @IsDefined()
  @IsString()
  public type!: string;

  @IsDefined()
  @ValidateNested()
  @Type(() => A)
  public nested!: A;
}
```

```js
// invalid request object with array (B[]) instead of object (B)
var requestObjB = {
   type: "test type"
   nested: [{ x: "test x" }] 
}
```

```js
// try to validate request object
validate(plainToClass(B, requestObjB))
```

**Validation failed and I get this error:**
```
 TypeError: newValue_1.push is not a function
    at /Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:67:34
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.transform (/Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:41:30)
    at _loop_1 (/Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:226:43)
    at TransformOperationExecutor.transform (/Users/bartosz/dev/user-data-api/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/Users/bartosz/dev/user-data-api/src/TransformOperationExecutor.ts:226:43)
    at TransformOperationExecutor.transform (/Users/bartosz/dev/user-data-api/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
```

Is it possible to solve this problem or maybe there is better way to handle this kind of validation?

**Comment by vlapo** [comment]
Same problem here. Its somehow related to using `@Type` in nested object. Failing example:
```typescript
import 'reflect-metadata';
import { Type, plainToClass } from 'class-transformer';

class Role {
  name: string;
}

class User {
  firstName: string;
  lastName: string;

  @Type(() => Role)
  roles: Role;

  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

class Example {
  @Type(() => User)
  users: User[] | null;
}


const payload = { 
  users: [ 
    { firstName: 'User', lastName: '#1', roles: [{name: 'r1'}]}, 
    { firstName: 'User', lastName: '#2', roles: []} 
  ] };
const transformed = plainToClass(Example, payload);

transformed.users.forEach(u => console.log(u.fullName));
```

**Comment by balkarov** [comment]
I have the same problem. Any idea?

**Comment by pumano** [comment]
fixed with:

```
@ValidateNested()
@Type(() => A)
public nested!: A;
```

but....it won't work if you don't import reflect metadata at root (I use it with vue js for frontend).
After proper import reflect metadata it works perfect.

**Comment by fabianoalmeida** [comment]
@pumano you're totally correct. I imported `reflect-metadata` and everything works fine. Thank you. 🙏

**Comment by NoNameProvided** [comment]
Closing as solved.
