### ISSUE TITLE
Type relation attribute

### ISSUE THREAD

**Issue by baudev** [typestack/class-transformer#290]
I'm facing an issue concerning the relations.

In my class I have the attribute `hydra:view`, which is is related to HydraViewObject. As you can see, the attribute is surrounded by quotation marks (") because the attribute name contains a particular character which is the semicolon (;).
```typescript
@Type(() => HydraViewObject)
readonly "hydra:view"?: HydraViewObject;
```

I can't rename this attribute in my backend. However, when using `plaintToClass` method, I got the following error:

```typescript
TypeError: Property value expected type of string but got null

      at Object.validate (node_modules/@babel/types/lib/definitions/utils.js:161:13)
      at validate (node_modules/@babel/types/lib/validators/validate.js:17:9)
      at builder (node_modules/@babel/types/lib/builders/builder.js:46:27)
      at Object.StringLiteral (node_modules/@babel/types/lib/builders/generated/index.js:335:31)
      at PluginPass.AssignmentExpression (node_modules/@babel/plugin-proposal-decorators/lib/transformer-legacy.js:167:167)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
```

The problem is due to the fact that the attribute is declared between quotations. I tried an attribute without guillement and the relationship works perfectly.

Do you have any idea how to do that?

**Comment by baudev** [comment]
See: [Exposing properties with different names](https://github.com/typestack/class-transformer#exposing-properties-with-different-names)

```typescript
    @Type(() => HydraViewObject)
    @Expose({ name: "hydra:view" })
    readonly hydraview?: HydraViewObject;
```
