### ISSUE TITLE
fix: plainToClass throws an error when a union-type member is undefined

### ISSUE THREAD

**Issue by tmtron** [typestack/class-transformer#520]
### Description

**Minimal code-snippet showcasing the problem**
 

```ts
  it('should deserialize undefined union type to undefined', () => {
    defaultMetadataStorage.clear();
    expect(() => {
      abstract class Hobby {
        public name: string;
      }

      class Sports extends Hobby {
        // Empty
      }

      class Relaxing extends Hobby {
        // Empty
      }

      class Programming extends Hobby {
        @Transform(({ value }) => value.toUpperCase())
        specialAbility: string;
      }

      class Person {
        public name: string;

        @Type(() => Hobby, {
          discriminator: {
            property: '__type',
            subTypes: [
              { value: Sports, name: 'sports' },
              { value: Relaxing, name: 'relax' },
              { value: Programming, name: 'program' },
            ],
          },
        })
        public hobby: Hobby;
      }
      
      const model: Person = new Person();
      const sport = new Sports();
      sport.name = 'Football';
      const program = new Programming();
      program.name = 'typescript coding';
      program.specialAbility = 'testing';
      model.name = 'John Doe';
      // NOTE: hobby remains undefined
      model.hobby = undefined;
      const json: any = classToPlain(model);
      expect(json).not.toBeInstanceOf(Person);
      expect(json.hobby).toBeUndefined();
    }).not.toThrow();
  });  
```

### Expected behavior
`plainToClass` should not throw an error and the plain JSON object should have the property set to `undefined`

### Actual behavior
Version: `0.3.1`  throws this error:

```
[Error: expect(received).not.toThrow()

Error name:    "TypeError"
Error message: "Cannot read property 'constructor' of undefined"

      216 |                 if (this.transformationType === TransformationType.CLASS_TO_PLAIN) {
      217 |                   subValue[metadata.options.discriminator.property] = metadata.options.discriminator.subTypes.find(
    > 218 |                     subType => subType.value === subValue.constructor
          |                                                           ^
      219 |                   ).name;
      220 |                 }
      221 |               } else {

      at src/TransformOperationExecutor.ts:218:59
          at Array.find (<anonymous>)
      at TransformOperationExecutor.transform (src/TransformOperationExecutor.ts:217:111)
      at ClassTransformer.classToPlain (src/ClassTransformer.ts:21:21)
      at Object.classToPlain (src/index.ts:21:27)
      at test/functional/custom-transform.spec.ts:565:25
      at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:84:11)
      at Object.throwingMatcher [as toThrow] (node_modules/expect/build/index.js:338:21)
      at Object.<anonymous> (test/functional/custom-transform.spec.ts:568:12)

    at Object.<anonymous> (D:\dev_no_backup\class-transformer-tmtron\test\functional\custom-transform.spec.ts:568:12)
    at Object.asyncJestTest (D:\dev_no_backup\class-transformer-tmtron\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at D:\dev_no_backup\class-transformer-tmtron\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (D:\dev_no_backup\class-transformer-tmtron\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at D:\dev_no_backup\class-transformer-tmtron\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (internal/process/task_queues.js:93:5)](url)



```

**Comment by NoNameProvided** [comment]
Fixed in 818897b58cc26d0bbebc09ddf9ac7a1ad94b6785. Will be includedi in the next release.
