### ISSUE TITLE
problem of passing an object which prototype is null to plainToClass

### ISSUE THREAD

**Issue by ruiming** [typestack/class-transformer#64]
Take this for example
```typescript
export class TestClass {
  @IsNumberString() public limit: string
  @IsNumberString() public offset: string
  @IsIn(['asc', 'desc']) public order: string
  @IsString() public sortby: string
}

const testObject = {
  limit: '1',
  offset: '2',
  order: 'asc',
  sortby: 'asd'
}
Reflect.setPrototypeOf(testObject, null) // Change the prototype of testObject to null
const test = plainToClass(TestClass, testObject)
const errors = await validate(test)
console.log(errors)
```
This will throw an Error:
```
ERROR:  TypeError: Cannot read property 'prototype' of undefined
    at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/metadata/MetadataStorage.ts:79:36
    at Array.filter (native)
    at MetadataStorage.getTargetValidationMetadatas (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/metadata/MetadataStorage.ts:75:61)
    at ValidationExecutor.execute (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/validation/ValidationExecutor.ts:44:54)
    at Validator.coreValidate (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/validation/Validator.ts:31:18)
    at Validator.validate (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/validation/Validator.ts:56:21)
    at Object.validate (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/index.ts:48:44)
    at ProblemsController.<anonymous> (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/controller/problems.ts:27:21)
    at Generator.next (<anonymous>)
    at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/controller/problems.ts:19:71
    at Promise (<anonymous>)
    at __awaiter (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/controller/problems.ts:15:12)
    at ProblemsController.index (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/controller/problems.ts:48:16)
    at ActionMetadata.callMethod (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/metadata/ActionMetadata.ts:254:62)
    at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/RoutingControllers.ts:123:142
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:86:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```
And If I delete this line `Reflect.setPrototypeOf(testObject, null)`, everything work well.
The reason I set prototype of test to null is that I use `@QueryParams` from `routing-controller` to validate `ctx.query` throwing same error. And the prototype of `ctx.query` points to null.
```typescript
export class ProblemQuery {
  @IsNumberString() public limit: string
  @IsNumberString() public offset: string
  @IsIn(['asc', 'desc']) public order: string
  @IsString() public sortby: string
}

@JsonController('/v1/problems')
export class ProblemsController {
  @Get('/')
  public async index (@Ctx() ctx: Context, @QueryParams('query') query: ProblemQuery) {
    // @QueryParams('query') query: ProblemQuery no work and throw same error above
    const problems = await ctx.services.problems.list(
      parseInt(query.offset), parseInt(query.limit), query.sortby, query.order
    )
    ctx.ok(problems)
  }
}
```
And `routing-controller` is using this package. So I think this problem should be solved here.

Thanks.

**Comment by NoNameProvided** [comment]
Hi @ruiming! 

This has been fixed in 0cd39ed, and will be included in the next release!

Thanks for your patience.
