### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined when serializing an object of objects

### ISSUE THREAD

**Issue by exoer** [typestack/class-transformer#918]
### Description
Serialize an object of object (e.g. `photosById: Record<string, Photo>`)  of a type with a `discriminator` gives

```
TypeError: Cannot read property 'name' of undefined
    at TransformOperationExecutor.transform 
```

**Minimal code-snippet showcasing the problem**
```
export abstract class Photo {
  id: number;
  filename: string;
  constructor(id: number, filename: string) {
    (this.id = id), (this.filename = filename);
  }
}

export class Landscape extends Photo {
  panorama: boolean;
  constructor(id: number, filename: string, panorama: boolean) {
    super(id, filename);
    this.panorama = panorama;
  }
}

export class UnderWater extends Photo {
  depth: number;
  constructor(id: number, filename: string, depth: number) {
    super(id, filename);
    this.depth = depth;
  }
}

class MyClass {

  @Type(
    (x) => {
      // console.log('x', x?.object[x.property]);
      return Photo;
    }
   //  ------- This is the code that fails 
    // {
    //   discriminator: {
    //     property: '__type',
    //     subTypes: [
    //       { value: Landscape, name: 'landscape' },
    //       // { value: Portrait, name: 'portrait' },
    //       { value: UnderWater, name: 'underwater' },
    //     ],
    //   },
    // }
  )
  photosById: Record<string, Photo>;
  @Type(
    (x) => {
      // console.log('yy', x?.object[x.property]);
      return Photo;
    },
    {
      discriminator: {
        property: '__type',
        subTypes: [
          { value: Landscape, name: 'landscape' },
          // { value: Portrait, name: 'portrait' },
          { value: UnderWater, name: 'underwater' },
        ],
      },
    }
  )
  photo: Photo;
  @Type(
    (x) => {
      // console.log('zz', x?.object[x.property]);
      return Photo;
    },
    {
      discriminator: {
        property: '__type',
        subTypes: [
          { value: Landscape, name: 'landscape' },
          // { value: Portrait, name: 'portrait' },
          { value: UnderWater, name: 'underwater' },
        ],
      },
    }
  )
  photosArr: Photo[];


  constructor(
    photosById: Record<string, Photo>,
    photo: Photo,
    photosArr: Photo[]
  ) {
    this.photosById = photosById;
    this.photo = photo;
    this.photosArr = photosArr;
  }
}

const p1 = new UnderWater(1, 'uw', 22);
const p2 = new Landscape(2, 'land', false);

const m1 = new MyClass({ p1: p1, p2 }, p1, [p1, p2]);

const nodeJson = serialize(m1);
```

### Expected behavior
I expect to serialize `photosById` object. with `__type`

```
{
  photosById: {
    p1: { id: 1, filename: 'as', depth: 22 },
    p2: { id: 2, filename: 'land', panorama: false }
  },
  photo: { id: 1, filename: 'as', depth: 22, __type: 'underwater' },
  photosArr: [
    { id: 1, filename: 'as', depth: 22, __type: 'underwater' },
    { id: 2, filename: 'land', panorama: false, __type: 'landscape' }
  ]
}

```

### Actual behavior
I get an error when I specify the `discriminator` option
```
TypeError: Cannot read property 'name' of undefined
    at TransformOperationExecutor.transform 

TransformOperationExecutor.ts:231:20
```

**Comment by Aerobraking** [comment]
I got the same error when I had a circular dependency between my .ts File that contains the "object of objects" class and the other .ts File that contains the objects classes. 

Mabye that helps?

**Comment by alcalyn** [comment]
I have this error with:

``` ts
@Type(() => Parent, {
    keepDiscriminatorProperty: true,
    discriminator: {
        property: 'type',
        subTypes: [
            { value: A, name: 'a' },
            { value: B, name: 'b' },
            { value: C, name: 'c' },
            { value: D, name: 'd' },
        ],
    },
})
abcd: Parent;
```

But it works when I do the discriminator myself like this:

``` ts
@Type((type) => {
    switch (type?.object.abcd.type) {
        case 'a': return A;
        case 'b': return B;
        case 'c': return C;
        case 'd': return D;
        default: return Parent;
    }
})
abcd: Parent;
```

The "Parent" class being like:

``` ts
export class Parent
{
    @Expose()
    @IsString()
    type: string;

    @Expose()
    @ValidateNested()
    options: object;
}
```

stack trace:
```
TypeError: Cannot read properties of undefined (reading 'name')
  at TransformOperationExecutor.transform (node_modules/src/TransformOperationExecutor.ts:250:22)
  at TransformOperationExecutor.transform (node_modules/src/TransformOperationExecutor.ts:327:31)
  at <anonymous> (node_modules/src/TransformOperationExecutor.ts:79:30)
  at Array.forEach (<anonymous>)
  at TransformOperationExecutor.transform (node_modules/src/TransformOperationExecutor.ts:44:24)
  at ClassTransformer.instanceToPlain (node_modules/src/ClassTransformer.ts:25:21)
  at instanceToPlain (node_modules/src/index.ts:35:27)
  at ExpressDriver.transformResult (node_modules/src/driver/BaseDriver.ts:108:31)
  at ExpressDriver.handleSuccess (node_modules/src/driver/express/ExpressDriver.ts:262:19)
  at <anonymous> (node_modules/src/RoutingControllers.ts:164:35)
```

**Comment by NilsMoller** [comment]
I'm seeing this with a circular reference as well. 

For me, the problem is in `TransformOperationExecutor#transform` on line 72 ([permalink](https://github.com/typestack/class-transformer/blob/a2734a5d154c9b0beb9a10555a04416bc371de06/src/TransformOperationExecutor.ts#L72)). 

The subtypes array have values like this: 
```ts
[
  { 
    name: "ClassA", 
    value: ClassA
  },
  {
    name: "ClassB",
    value: undefined,
  },
]
```

This shows the `ClassB` constructor missing as the value, causing line 72/73 to throw this error.
